services:
  - type: web
    name: crop-recommendation-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wkhtmltopdf
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
